{% set version = "2.0.2" %}

package:
  name: aesara
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: bccba77e44f9862e01960a648ecab364b88a3691184f0ea2cc692e73b40ca540
  patches:

build:
  number: 2
  entry_points:
    - aesara-cache = bin.aesara_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.7.0,<0.8
    - jax  # [py>=37 and not win]
    - filelock

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

about:
  home: https://github.com/pymc-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions. Aesara is a fork of the Theano library maintained by the PyMC developers.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
