{% set version = "2.7.4" %}

package:
  name: aesara-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 852374405f5eaf7c52703034093a7bbbf9bc05bf3acd6b1e3e6d6b0cf5aa3680
  patches:

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
  run:

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

outputs:
  - name: aesara-base
    build:
      script:
        - python -m pip install . --no-deps -vv
      entry_points:
        - aesara-cache = bin.aesara_cache:main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - python
        # Ref: <https://github.com/aesara-devs/aesara/blob/rel-{{ version }}/setup.py>
        - numpy>=1.17.0
        - scipy>=0.14
        - filelock
        - etuples
        - logical-unification
        - miniKanren
        - cons
        - typing_extensions
    test:
      imports:
        - aesara
      commands:
        - aesara-cache help
        - python check-for-warnings.py allowed-warnings-base.txt
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt
  - name: aesara
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('aesara-base', exact=True) }}
        - {{ compiler('c') }}  # [not win]
        - cxx-compiler  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
        # Use openblas on Apple M1 or pypy3.7. For everything else, use mkl-service.
        - openblas  # [arm64 or (python_impl == 'pypy' and py==37)]
        - mkl-service  # [not (arm64 or (python_impl == 'pypy' and py==37))]
        # For some reason we also need the "blas" package. Otherwise we get reports
        # of "cblas.h: No such file or directory" at import time.
        # Ref: <https://github.com/conda-forge/aesara-feedstock/issues/80>
        - blas  # [not (win and python_impl == 'pypy' and py==37)]
        # Note: we should probably drop pypy3.7 support since it seems a bit screwy,
        # and 3.8/3.9 are already out.
    test:
      imports:
        - aesara
      commands:
        - aesara-cache help
        - python check-for-warnings.py allowed-warnings-main.txt
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - ricardoV94
    - brandonwillard
