{% set version = "2.9.4" %}

package:
  name: aesara-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 704eecf24a0165b2eefcf23539eb0f0c5973081ee3b9ecd8a97b80e1f301ad7a
  patches:

build:
  number: 1
  # <https://github.com/conda-forge/scipy-feedstock/issues/249>
  skip: true  # [(win and (python_impl == 'pypy')) or py>311]

outputs:
  - name: aesara-base
    build:
      script:
        - python -m pip install . --no-deps -vv --prefix ${PREFIX}  # [aarch64]
        - python -m pip install . --no-deps -vv  # [not aarch64]
      entry_points:
        - aesara-cache = aesara.bin.aesara_cache:main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - hatchling >=1.11.1,<2.0.0
        - hatch-vcs >=0.3.0,<0.4.0
        - pip
      run:
        - python

        # Ref: <https://github.com/aesara-devs/aesara/blob/rel-{{ version }}/setup.py>
        - numpy>=1.17.0,<2.0.0
        - scipy>=0.14,<=1.12.0
        - filelock
        - etuples
        - logical-unification
        - miniKanren
        - cons
        - typing_extensions
        - setuptools >=48.0.0
    test:
      imports:
        - aesara
      commands:
        - aesara-cache help
        - pip check
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt
  - name: aesara
    build:
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('aesara-base', exact=True) }}
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('cxx') }}  # [not win and not linux]
        - gxx  # [linux]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]

        - m2w64-toolchain  # [win]
        # The libpython conda-forge package seems to be a wrapper package
        # which configures m2w64-toolchain for Python.
        # <https://github.com/conda-forge/libpython-feedstock/blob/main/recipe/bld.bat>
        - libpython >=2.2  # [win]

        # Use openblas on Apple M1. For everything else, use mkl-service.
        - openblas  # [arm64 or aarch64]
        - mkl-service  # [not arm64 and not aarch64]
        # For some reason we also need the "blas" package. Otherwise we get reports
        # of "cblas.h: No such file or directory" at import time.
        # Ref: <https://github.com/conda-forge/aesara-feedstock/issues/80>
        - blas
    test:
      imports:
        - aesara
        - aesara.configdefaults
      commands:
        - aesara-cache help
        - pip check
        # BLAS is not found for Windows for unknown reasons.
        # See <https://github.com/conda-forge/aesara-feedstock/pull/137#issuecomment-2317292602>
        # Ignore this problem for now by adding a selector to only test when on Windows
        - python check-for-warnings.py allowed-warnings-main.txt  # [not win]
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
    - rlouf
    - dgerlanc
