{% set version = "2.3.0" %}

package:
  name: aesara
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 35a6edcc982d59d79c9b768091ecde5e4b6e634b294555331cb081d3711f4b1d
  patches:

build:
  number: 0
  entry_points:
    - aesara-cache = bin.aesara_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - libblas
    - liblapack
  run:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - filelock
    - libpython >=2.0  # [win]
    - dataclasses  # [py36]

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
