{% set version = "2.5.2" %}

package:
  name: aesara
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 8168b9feff41bfe946306a63f8e8d1bc59b82f0c862c1a7147ca1eece18e8a89
  patches:

build:
  number: 0
  entry_points:
    - aesara-cache = bin.aesara_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - blas
    - libblas
    - liblapack
  run:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14,<1.8.0
    - filelock
    - libpython >=2.0  # [win]
    - dataclasses  # [py==36]
    - logical-unification
    - miniKanren
    - cons
    - etuples
    - typing_extensions

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
