{% set version = "2.8.12" %}

package:
  name: aesara-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 222f3a2b37ca67bc74bde08135d5a56b7a566dbb9073651181400c652ea15adb
  patches:

build:
  number: 1

outputs:
  - name: aesara-base
    build:
      script:
        - python -m pip install . --no-deps -vv --prefix ${PREFIX}  # [aarch64]
        - python -m pip install . --no-deps -vv  # [not aarch64]
      entry_points:
        - aesara-cache = aesara.bin.aesara_cache:main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy >=1.17.0                         # [build_platform != target_platform]
        - setuptools-scm                         # [build_platform != target_platform]
        - tomli                                  # [build_platform != target_platform]
        - setuptools >=61.2                      # [build_platform != target_platform]
      host:
        - pip
        - python
        - cython
        - numpy >=1.17.0
        - setuptools-scm
        - tomli
        - setuptools >=61.2
      run:
        - python

        # Ref: <https://github.com/aesara-devs/aesara/blob/rel-{{ version }}/setup.py>
        - numpy>=1.17.0
        - scipy>=0.14
        - filelock
        - etuples
        - logical-unification
        - miniKanren
        - cons
        - typing_extensions
        - setuptools >=48.0.0
    test:
      imports:
        - aesara
      commands:
        - aesara-cache help
        - pip check
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt
  - name: aesara
    build:
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('aesara-base', exact=True) }}
        - {{ compiler('c') }}  # [not win]
        - cxx-compiler  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]

        - m2w64-toolchain  # [win]
        # The libpython conda-forge package seems to be a wrapper package
        # which configures m2w64-toolchain for Python.
        # <https://github.com/conda-forge/libpython-feedstock/blob/main/recipe/bld.bat>
        - libpython >=2.2  # [win]

        # Use openblas on Apple M1. For everything else, use mkl-service.
        - openblas  # [arm64 or aarch64]
        - mkl-service  # [not arm64 and not aarch64]
        # For some reason we also need the "blas" package. Otherwise we get reports
        # of "cblas.h: No such file or directory" at import time.
        # Ref: <https://github.com/conda-forge/aesara-feedstock/issues/80>
        - blas
    test:
      imports:
        - aesara
        - aesara.configdefaults
      commands:
        - aesara-cache help
        - pip check
        - python check-for-warnings.py allowed-warnings-main.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
    - rlouf
    - dgerlanc
