{% set version = "2.7.3" %}

package:
  name: aesara-suite  # https://github.com/conda/conda-build/issues/3933
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: 6626aec09b2b10ee8fd113d4dc42e4606c82a1d96031ae5730165b5b35b890ca
  patches:

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
  run:

test:
  imports:
    - aesara
  commands:
    - aesara-cache help

outputs:
  - name: aesara-base
    build:
      script:
        - python -m pip install . --no-deps -vv
      entry_points:
        - aesara-cache = bin.aesara_cache:main
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
        - blas
        - libblas
        - liblapack
      run:
        - python
        - setuptools
        - six >=1.9.0
        - numpy >=1.9.1
        - scipy >=0.14
        - filelock
        - libpython >=2.0  # [win]
        - dataclasses  # [py==36]
        - logical-unification
        - miniKanren
        - cons
        - etuples
        - typing_extensions
    test:
      imports:
        - aesara
      commands:
        - aesara-cache help
  - name: aesara
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('aesara-base', exact=True) }}
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('cxx') }}  # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - ricardoV94
    - brandonwillard
