{% set version = "2.7.1" %}

package:
  name: aesara
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aesara/aesara-{{ version }}.tar.gz
  sha256: b5f55bc312c94222a0b1fee4a4fec85a22accb1ce47bb7772d035bcdb3f3f6eb
  patches:

build:
  number: 1
  entry_points:
    - aesara-cache = bin.aesara_cache:main
  script: {{ PYTHON }} -m pip install . -vv
  # TODO: DELETE THIS AND RERENDER!!!
  skip: true  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - blas
    - libblas
    - liblapack
  run:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - mkl-service  # [win]
    - libpython  # [win]
    - m2w64-toolchain  # [win]
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14,<1.8.0
    - filelock
    - libpython >=2.0  # [win]
    - dataclasses  # [py==36]
    - logical-unification
    - miniKanren
    - cons
    - etuples
    - typing_extensions

test:
  imports:
    - aesara
  commands:
    - aesara-cache help
    - python check-for-warnings.py
  files:
    - check-for-warnings.py

about:
  home: https://github.com/aesara-devs/aesara
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/aesara-devs/aesara/
  doc_url: https://aesara.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - ricardoV94
    - brandonwillard
